services:
  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html

  web:
    image: nginx:latest
    volumes:
      - ./app:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mysql

  composer:
    image: composer
    volumes:
      - ./app:/app
    working_dir: /app
    tty: true
    stdin_open: true

volumes:
  dbdata:
